### ISSUE TITLE
wrong branch names

### ISSUE THREAD

**Issue by gerritvanos** [R2D2-2019/microphone#1]
could you delete the develop branch this is not part of the workflow
the audio-sensor branch does not have feature- in front and does not use underscore's please fix this

**Comment by gerritvanos** [comment]
sorry closed the wrong issue

**Comment by gerritvanos** [comment]
contacted brandon (current scrummaster of this module) about the issue

**Comment by ghost** [comment]
i have deleted both branches. the audio sensor probably wont be used. and the develop branch is not up to date anyway.
